In [189]:
from more_itertools import distinct_permutations
import numpy as np

n = 6
s1 = 3
s2 = 3

a = np.concatenate((np.ones(s1),np.zeros(n-s1)))
b = np.concatenate((np.ones(s2),np.zeros(n-s2)))
print(a,b)

p_a = np.array(tuple(distinct_permutations(a)))
p_b = np.array(tuple(distinct_permutations(b)))
#print(p_a,"\n\n", p_b)

p_aa = np.repeat(p_a, p_b.shape[0], axis=0)
p_bb = np.tile(p_b, (p_a.shape[0],1))

base = np.concatenate((p_aa, p_bb), axis=1)

[1. 1. 1. 0. 0. 0.] [1. 1. 1. 0. 0. 0.]


In [213]:
x = np.arange(10)
x = base[1]
x

array([0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1.])

In [216]:
print(up(x))
print(down(x))
nn(x)


[0. 0. 0. 1. 1. 1.]
[0. 0. 1. 0. 1. 1.]


2.0

In [223]:
def up(x): return x[: x.size//2]
def down(x): return x[x.size//2 : ]
def nn(x): return np.sum(up(x) * down(x))
def diag(basis, i): return basis[:,i] * basis[:, 2*n//2 + i]

In [227]:
np.diag((diag(base, 2))).shape

(400, 400)

In [218]:
base[:,0] * base[:, n//2]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1.