general todo, organize class, maybe subclass, some static methods
write documentation

## Import all the relevant Modules 

In [1]:
%matplotlib inline

# adding `Modules/` to the system path
#import sys
#sys.path.insert(0, './Modules/')

#TODO: Rename module shortcuts such as hb into something usefull after development
import Modules.Hubbard_Class as hb
import Modules.Widgets as w
import ipywidgets as widgets
import numpy as np

# Plotting
import matplotlib.pyplot as plt
plt.style.use('seaborn-dark')
plt.rcParams.update({'font.size':14})

from ipywidgets import HBox, VBox
import functools

%load_ext autoreload
%autoreload 2
#TODO rename one of the modules folders

TODO: give a good description of the model we're looking at
## Introduction

The following are all markdown todos
* TODO: Check name of basis states
* TODO: Show how basis is created
* #TODO state that total number of basis states is ncr(n,s1) ncr (n,s2)
## The Fock Basis states 

In [2]:
h1 = hb.Hubbard()


In [3]:
basis_widget = widgets.interactive(h1.show_basis, index=h1.basis_index, n=h1.n, s_up=h1.s_up, s_down=h1.s_down);

display(basis_widget)
#TODO check how to close all widgets, even if they are not already opened

interactive(children=(BoundedIntText(value=6, description='State $=$', layout=Layout(width='3cm'), max=399, st…

## Hopping Hamiltonian

Markdown Taks:
* TODO: possibly show the simple n=2 analytic calculation for the hubbard molecule in occupation number basis
* TODO: Show the operator nn, na, nb etc


* TODO: Show the operator nn, na, nb etc, show S_a. S_b, S^2

* TODO: Do not show hopping, boring!

In the Widget below one can play around with the number of sites $n$, spin up and spin down states, as well as the interaction strength $U$ and the hopping amplitude $t$ to explore the hamiltonian $H$. Note that only for $n \leq 4$ the complete matrix can be fully displayed.

In [4]:
#close previous widget to prevent slowing down calculations
basis_widget.close()

np.set_printoptions(linewidth=150) #set output length, default=75
H_widget = widgets.interactive(h1.Show_H, u=h1.u, t=h1.t, n=h1.n, s_up=h1.s_up, s_down=h1.s_down);
display(H_widget)

interactive(children=(FloatSlider(value=2.0, continuous_update=False, description='$U=$', max=5.0, min=-5.0, r…

# Calculate Eigenenergies 
TODO: for Hu in widget (copy paste)
TODO: for Ht with widget (copy paste) 

In [5]:
# adding `Modules/` to the system path
import sys
sys.path.insert(0, '../Modules/')

from Module_Widgets_and_Sliders import Text_Box, Save_Figure_Button, Click_Save_Figure, set_filename#
#from Widgets import steps_Slider

In [11]:
H_widget.close()

Hu_widget = widgets.interactive(h1.Plot_Eigvals_Hu, u=h1.u_range, n=h1.n, s_up=h1.s_up, s_down=h1.s_down);

filename = set_filename("Hubbard.pdf")
Save_Figure_Button.on_click(functools.partial(Click_Save_Figure, widget=Hu_widget, name_widget=filename, output=h1.out, path=""))

display(HBox([Save_Figure_Button, filename, h1.out]))
display(Hu_widget)

interactive(children=(FloatRangeSlider(value=(2.0, 40.0), continuous_update=False, description='todo:', max=40…

In [22]:
h1.Calc_Eigvals_u()

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.
 14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5
 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40. ]


(array([[-5.85410197, -5.85410197, -4.47213595, ...,  4.47213595,  5.85410197,  5.85410197],
        [-5.27697927, -5.27697927, -3.90852483, ...,  5.10694688,  6.47592899,  6.47592899],
        [-4.74754482, -4.74754482, -3.41855072, ...,  5.80642385,  7.13923859,  7.13923859],
        ...,
        [-0.31902046, -0.31902046, -0.20472511, ..., 80.10236427, 80.15575901, 80.15575901],
        [-0.31500146, -0.31500146, -0.20214363, ..., 81.10107344, 81.15258396, 81.15258396],
        [-0.31108223, -0.31108223, -0.19962632, ..., 82.09981471, 82.14948718, 82.14948718]]),
 array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. ,
        11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5,
        23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 3

In [21]:
np.unique(np.diag(h1.Op_n), return_counts=True)

(array([0., 1., 2.]), array([10, 60, 30]))

In [44]:
np.linspace(0,5, num=6).reshape(1,-1).shape

(1, 6)